const theme = {
  colors: {
    primary: '#00236f',
    primaryLight: '#dce1ff',
    primaryContainer: '#1e3a8a',
    onPrimary: '#ffffff',
    onPrimaryFixed: '#00164e',
    onPrimaryFixedVariant: '#264191',
    primaryFixedDim: '#b6c4ff',
    background: '#f7f9fb',
    surface: '#f7f9fb',
    surfaceBright: '#f7f9fb',
    surfaceDim: '#d8dadc',
    surfaceContainer: '#eceef0',
    surfaceContainerLow: '#f2f4f6',
    surfaceContainerHigh: '#e6e8ea',
    surfaceContainerHighest: '#e0e3e5',
    surfaceContainerLowest: '#ffffff',
    onSurface: '#191c1e',
    onSurfaceVariant: '#444651',
    onBackground: '#191c1e',
    inverseSurface: '#2d3133',
    inverseOnSurface: '#eff1f3',
    inversePrimary: '#b6c4ff',
    secondary: '#505f76',
    secondaryContainer: '#d0e1fb',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#54647a',
    secondaryFixed: '#d3e4fe',
    secondaryFixedDim: '#b7c8e1',
    onSecondaryFixed: '#0b1c30',
    onSecondaryFixedVariant: '#38485d',
    tertiary: '#00311f',
    tertiaryContainer: '#004a31',
    onTertiary: '#ffffff',
    tertiaryFixed: '#6ffbbe',
    tertiaryFixedDim: '#4edea3',
    onTertiaryFixed: '#002113',
    onTertiaryFixedVariant: '#005236',
    error: '#ba1a1a',
    errorContainer: '#ffdad6',
    onError: '#ffffff',
    onErrorContainer: '#93000a',
    success: '#1a7f37',
    warning: '#b25e00',
    outline: '#757682',
    outlineVariant: '#c5c5d3',
    surfaceTint: '#4059aa',
    star: '#fbbc04',
    statusAvailable: '#e8f5e9',
    statusRented: '#fff3e0',
    statusMaintenance: '#fce4ec',
    statusReserve: '#dce1ff',
    sidebarBg: 'rgba(248,250,252,0.8)',
    sidebarBorder: '#e2e8f0',
    navInactive: '#64748b',
    navHover: 'rgba(226,232,240,0.5)',
    navActiveBg: '#00236f',
    navActiveText: '#ffffff',
  },
  fonts: {
    headline: 'Manrope_400Regular',
    headlineBold: 'Manrope_700Bold',
    body: 'Inter_400Regular',
    bodyMedium: 'Inter_500Medium',
    bodySemibold: 'Inter_600SemiBold',
    bodyBold: 'Inter_700Bold',
    label: 'Inter_500Medium',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 999,
  },
  fontSize: {
    xs: 11,
    sm: 13,
    md: 15,
    lg: 17,
    xl: 20,
    xxl: 24,
    title: 28,
  },
  shadow: {
    card: {
      shadowColor: '#191c1e',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 2,
    },
    editorial: {
      shadowColor: '#191c1e',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.06,
      shadowRadius: 32,
      elevation: 8,
    },
  },
};

export default theme;
